### ISSUE TITLE
Filter isn't removing the extra filtering

### ISSUE THREAD

**Issue by timalmond** [zzzprojects/EntityFramework.DynamicFilters#124]
I tried using the EnableFilter query and use a lambda with a function to check user level and filter as required. This function returned false, but the filter still navigated to entities that weren't required.

I found that I had to add a statement into BuildFilterExpressionWithDynamicFilters of 

(!_DbContext.IsFilterEnabled(filter.FilterName)) continue;

for each filter in filterList for this to work.

I'm certain I'm doing something wrong with the configuration of DynamicFilters rather than your code, but I can't see what's wrong. I also noticed from the source that methods like PreventAllDisabledFilterConditions in DynamicFilterExtensions were not being called but I don't know why.

**Comment by JonathanMagnan** [comment]
Hello @timalmond ,

Do you think you could submit us a small example?

By example, check this example: https://github.com/zzzprojects/EntityFramework.DynamicFilters/issues/72#issuecomment-331672195

It will help us to getting started and better understand this problem.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @timalmond ,

I will close this issue since no example has been provided.

If you can provide one, please reopen this issue and we will work on it.

Best Regards,

Jonathan
