### ISSUE TITLE
Unity/ Using Dependency Injection

### ISSUE THREAD

**Issue by h7meshpatel** [zzzprojects/EntityFramework.DynamicFilters#128]
Hi,

We're trying to use dependency injection to get a global object. We're finding that the http context is null and therefore creating a new instance of the class.

```csharp
modelBuilder.Filter(DefinedFilter.Context_Retailers.ToString(), (IRetailerFilterOrganisationId d, List<int> valueList) 
	=> valueList.Contains(d.OrganisationId), (BritanniaOnlineEntities dbContext) 
		=> FilterDelegates.GetContextRetailers(DefinedFilter.Context_Retailers, dbContext));
```

this would then call (please see bold remark)

```csharp
public static List<int> GetContextRetailers(DefinedFilter thisFilter, BritanniaOnlineEntities dbContext)
{
	using (var fs = new FilterState(dbContext))
	{
		if (!fs.IsFilterEnabled(thisFilter)) //prevent circular calls
		{
			return null; //doesnt matter what we return - filter is disabled.
		}

		fs.PauseFilter(thisFilter);               

		var currentContext = DependencyResolver.Current.GetService<ApplicationContext>(); **// di returns a brand new object**
		var retailerIds = currentContext.GetAllowedRetailerIds(dbContext);                

		if (retailerIds == null)
		{
			// null means all are allowed. turn off the filter for this request
			fs.SetFilterState(thisFilter, false);
			return new List<int>();
		}
		else
		{
			return retailerIds;
		}
	}
}
```

In unity we are using the normal container and this object is registers with a PerRequestLifetimeManager. We would like this object to not be disposed of for the whole lifetime of the request.

Any idea on how we stop the filter delegate from creating a new object every time. I know this may fall in unity config but any advice is appreciated.

Thanks
Himesh

**Comment by JonathanMagnan** [comment]
Honestly, it doesn't look at all a problem related to EF DynamicFilters but more how you use your Dependency Injection as you specified.

On the library side, we are not aware of anything related to a request, so there is nothing we can do I believe about `not be disposed`.

I'm not sure to either understand fully this request. Which object don't you want not to be disposed of? From my understanding, the ApplicationContext is already managed by your `PerRequestLifetimeManager`

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @h7meshpatel ,

Could we close this issue?

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by h7meshpatel** [comment]
Hi Jonathan

Yes please.

Thanks
Himesh



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
