### ISSUE TITLE
Conditionals in Lambda expressions are not supported

### ISSUE THREAD

**Issue by thinksjay** [zzzprojects/EntityFramework.DynamicFilters#129]
public interface IDataAuthorization
    {
        long? CreatorUserId { get; set; }
    }

    public class Project:IDataAuthorization
    {
        public long? CreatorUserId { get; set; }
    }

    public class RvteDbContext:AbpZeroDbContext<Tenant,Role,User>
    {
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Filter("DataAuthorization", (IDataAuthorization entity, List<long> userIds) => entity.CreatorUserId.HasValue && userIds.Count > 0 ? userIds.Contains(entity.CreatorUserId) : true, () => new List<long>());
        }
    }

    public class RvteDataModule:AbpModule
    {
        public override void PreInitialize()
        {
            Configuration.UnitOfWork.RegisterFilter("DataAuthorization", false);
        }
    }

    var project = await _projectRepository.FirstOrDefaultAsync(t => t.Name == "demoname");

    >>Error:Conditionals in Lambda expressions are not supported

**Comment by JonathanMagnan** [comment]
Hello @thinksjay ,

Unfortunately, the library have some limitation.

Under the hood, the library only change the expression but keep using the Entity Framework which doesn't support conditional.

Unless Entity Framework start supporting it, there is nothing we can do.

Let me know if that answer correctly to your request and if we can close it.

Best Regards,

Jonathan

**Comment by thinksjay** [comment]
Thanks
