### ISSUE TITLE
Configure For Database/Model First

### ISSUE THREAD

**Issue by romainecarter** [zzzprojects/EntityFramework.DynamicFilters#133]
Based on the documentation I see where the filters are configured through OnModelCreating override, Is there a way to do this using Database first?

**Comment by JonathanMagnan** [comment]
Unfortunately no,

You can use [EF+ Query Filter](http://entityframework-plus.net/query-filter) but it doesn't work as good as this library for by example `Tenant` scenario.

Let me know if that successfully answer your question.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by romainecarter** [comment]
Thanks I will look into EF + Query Filter.

**Comment by romainecarter** [comment]
Below example the filter is not added, is this one of the limitations you mentioned?

```csharp
using System;
using System.Data.Entity;
using System.Linq;
using Z.EntityFramework.Plus;
namespace DbContextAOP
{
    class Program
    {
        static void Main(string[] args)
        {
            QueryFilterManager.Filter<Employee>(q => q.Where(x => x.BusinessEntityID == 250));

            using (var db = new AdventureWorks2016CTP3Entities())
            {              
                var purchase = db.PurchaseOrderHeader.Include(a=>a.Employee).Select(i => i.Freight + " " +  i.Employee.BusinessEntityID);

                foreach (var m in purchase)
                {
                    Console.WriteLine(m);
                }
            }
        }
    }
}
```
Generated SQL 
```SQL
SELECT 
     CAST( [Extent1].[Freight] AS nvarchar(max)) + N' ' +  CAST( [Extent1].[EmployeeID] AS nvarchar(max)) AS [C1]
    FROM [Purchasing].[PurchaseOrderHeader] AS [Extent1]
```

**Comment by JonathanMagnan** [comment]
Hello @romainecarter ,

I believe you are missing the `QueryFilterManager.InitilizeGlobalFilter(ctx);` code.

Global filter is not applied by default. It's normally recommended to add it in your context constructor if you can.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by romainecarter** [comment]
Thanks @JonathanMagnan , I added that but getting the same results.

**Comment by romainecarter** [comment]
Seems adding a navigation property to the query as in the above example does not work and the where clause is dropped in the generated SQL.

**Comment by JonathanMagnan** [comment]
Hmmm,

Looking at the source code, we only support filtering list but recently, we added a new property `QueryFilterManager.AllowPropertyFilter = true;` which also to support navigation property that is not list but item.

Could you try with this option?

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by romainecarter** [comment]
That worked!

**Comment by JonathanMagnan** [comment]
That's great ;)

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_
