### ISSUE TITLE
Filter failure on association when parent class is part of TPT inheritance

### ISSUE THREAD

**Issue by mdoust** [zzzprojects/EntityFramework.DynamicFilters#135]
- Version 3.0.1

Consider the following classes and association:
```
public class Account
{
    public string Id {get; protected set;}
    public virtual SubscriberCard Card {get; protected set;}
    ...
}

public class Doctor : Account
{
    public bool IsSuspended {get; private set;}
    ...
}

public class SubscriberCard
{
        public virtual Account Account { get; private set; }
        ...
}
```

We have defined a filter on Doctor entity in order to list doctors who have not been suspended:
`` modelBuilder.Filter("DoctorsDefaultScope", (Doctor x) => x.IsSuspended, false); ``

We could not define this filter on the parent class (Account) because there are other children of Account for whom 'Suspension' has no meaning.

Say we have a SubscriberCard belonging to a suspended doctor. When we try to retrieve the doctor record through the association (by calling the card.Account and then casting it to a Doctor,) we would expect to get Null. But to our surprise doctor is retrieved successfully.

**So is this the expected behavior of the filter?**

After some investigation, we observed that if a given filter is defined on the Account class (and on a property common to all children,) then calling card.Account would indeed return null; off course if the associated account did not meet the filter criteria.

**Comment by JonathanMagnan** [comment]
Hello @mdoust ,

Thank you for reporting,

We will try to look at this request this week.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @mdoust ,

Unfortunately, we tried some scenario on our side but we are not able to support it.

The problem is the filter is done on the derived class and not on the base class.

So when querying the base class, there is nothing we can do as they can have multiple derived class.

What you can do on your side, is adding a new `DbSet<Doctor>` and getting value directly from it when you want to get a list of Doctor and get them filtered

```
var listDoctoc = context.Doctors.ToList(); // 1 result 
```

Let me know if that could solve your issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @mdoust ,

This issue will be closed since it has been resolved. We cannot, unfortunately, support this scenario

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
