### ISSUE TITLE
Does not work SKIP, TAKE and ORDER BY in queries without filtering, when DynamicFilter is used

### ISSUE THREAD

**Issue by dopusteam** [zzzprojects/EntityFramework.DynamicFilters#139]
Hello. We use dynamic filter and we faced up problem. All relevant information about used versions provided at the end.

We found some problem with using dynamic filter. When we trying to get all values from database with pagination and ordering, without any additional filtering (except dynamic filter), we get all rows from DB (pagination and ordering does not work).

However, if we add some filtering (even mindless), sorting and pagination works.

Our class looks like 

```
public class Entity {

	public long Id { get; set; }
	
	public long SortOrder { get; set; }
	
	public bool IsDeleted { get; set; }

}

```

1. Here is example of query without filtering

```
var query = this
	.Repository
	.GetAll()
	.OrderBy(entity => entity.SortOrder)
	.Skip(1)
	.Take(1);
```

here is sql command for this query (this is query for this point, I mean we have breakpoint here and we get this command from 'query' variable)

`SELECT "Var_1"."Id", "Var_1"."IsDeleted" FROM "public"."Entities" AS "Var_1" WHERE "Var_1"."IsDeleted" = @DynamicFilterParam_000001 OR @DynamicFilterParam_000002 IS NOT NULL ORDER BY "Var_1"."SortOrder" ASC  OFFSET 1 LIMIT 3`

hovewer further, when the actual query is executed, the sql command looks like

`SELECT "Var_1"."Id", "Var_1"."IsDeleted" FROM "public"."Entities" AS "Var_1" WHERE "Var_1"."IsDeleted" = @DynamicFilterParam_000001 "`

as you can see the last part of query lost.

2. Here is example of query with mindless filtering

```
var query = this
	.Repository
	.GetAll()
	.Where(entity => !entity.IsDeleted)
	.OrderBy(entity => entity.SortOrder)
	.Skip(1)
	.Take(1);

```
here is sql command for this query

`SELECT "Extent1"."Id", "Extent1"."IsDeleted" FROM "public"."Entities" AS "Extent1" WHERE ("Extent1"."IsDeleted" = @DynamicFilterParam_000001 OR @DynamicFilterParam_000002 IS NOT NULL) AND "Extent1"."IsDeleted" != TRUE ORDER BY "Extent1"."SortOrder" ASC  OFFSET 1 LIMIT 3`

and further, when the actual query is executed, the sql command looks like

`SELECT "Extent1"."Id", "Extent1"."IsDeleted" FROM "public"."Entities" AS "Extent1" WHERE ("Extent1"."IsDeleted" = @DynamicFilterParam_000001 ) AND "Extent1"."IsDeleted" != TRUE ORDER BY "Extent1"."SortOrder" ASC  OFFSET 1 LIMIT 3`

As you can see in this case everytinhg is OK.

We investigated this problem a little bit, and found out, that probably the reason in your RemoveFilterDisabledConditionFromQuery function in DynamicFilterExtensions class.

```
...

int endIdx = command.CommandText.IndexOf(")", paramIdx);

if (endIdx == -1)
{
	//  PostgreSQL does not wrap all conditions in () (see below for example) so we may not find this.
	//  So assume end of line.
	endIdx = command.CommandText.Length - 1;
}

....

command.CommandText = command.CommandText.Remove(startIdx, endIdx - startIdx + 1);

...
```

Since our first example does not contain any parentheses, this function removes all query part after @DynamicFilterParam_000002, as a result LIMIT, OFFSET and ORDER BY also removed.

Additional information:
1. DynamicFilter version is 1.4.11
2. We use postgres 9.5.5
3. NpgSql 3.2.5
4. EntityFramework6.NpgSql 3.1.1

We have single filter, presented below

```
protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
	modelBuilder.Filter(FilterName.SoftDelete, (ISoftDelete sd) => sd.IsDeleted, false);
}
```

Best Regards,

dopusteam

**Comment by dopusteam** [comment]
Hello @JonathanMagnan,

I will try to provide example project in few days

Best Regards,

dopusteam

**Comment by dopusteam** [comment]
Hello @JonathanMagnan,

I found that the problem is not reproduced starting from 2.0 version of dynamicFilters, so probably we will use newer version.
However, since it can be useful, I attach sample project with 1.4.11 version, where the problem is reproduced.

Thank you!

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Oh, I should have looked at the version you specified first ;)

Thank for the project

**Comment by JonathanMagnan** [comment]
Hello @Jon,

This issue will be closed since it has been resolved in latest version

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
