### ISSUE TITLE
Create filters with user-defined SQL Function calls

### ISSUE THREAD

**Issue by BerndSadleder** [zzzprojects/EntityFramework.DynamicFilters#149]
Hello,

currently `LambdaToDbExpressionVisitor` throws an `InvalidOperationException` if filter predicate includes a `MethodCallExpression` to a custom mapped DbFunction:

Here is a short example:

```cs
public static class MyDBFunctions
{
        [DbFunction("DataModel.Store", "CustomDBFunction")]
        public static bool CustomDBFunction(string value1, string value2)
        {
            throw new NotSupportedException("Direct calls not supported");
        }
}

var predicateExpression = (MyEntity e, string param) => MyDBFunctions.CustomDBFunction(param, e.Column);
```

How could i support such inline method calls to user-defined SQL Functions in my filter expressions?

**Comment by JonathanMagnan** [comment]
Hello @BerndSadleder ,

We will close this issue, it will stay open in our `wish list` but as said, we are no short-term plan for it.
