### ISSUE TITLE
Entity Framework Dynamic Filters not working in dot net core

### ISSUE THREAD

**Issue by kodithuwa** [zzzprojects/EntityFramework.DynamicFilters#160]
Hi,
I have installed DynamicFilters for my .net core project, but  also it asks to install EF 6.0,
Is it essential to install EF 6.0 for work DynamicFilters in dotnet core environment? 
My current EF Core version is 2.2.6
Thanks
Chaminda

**Comment by JonathanMagnan** [comment]
Hello @kodithuwa ,

The EF Dynamic Filter doesn't support yet EF Core.

I believe starting from EF Core 3.x, Microsoft re-added Interceptor so we could maybe try to make this feature compatible but at the same time, EF Core has their own filter logic so I'm not sure if that really worth the effort.

Let me know if that answers correctly to your question.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @kodithuwa 

Since our last conversation, we haven't heard from you. 

Did you get the time to try the the EF Core3.x?

Looking forward to hearing from you,

Jon

**Comment by ninetailedfox494** [comment]
Hi @JonathanMagnan,
I have the same issue. 
![image](https://user-images.githubusercontent.com/12892144/81417291-8c5bfe00-917d-11ea-9ba6-1e78620b033d.png)
my project use .net core 3.1.2 and installed DynamicFilters for my .net core project but it does not work and not found when injecting
Thanks,
Thuy Doan

**Comment by JonathanMagnan** [comment]
Hello @ninetailedfox494 ,

Unfortunately, we have not ported yet this library to EF Core. We might want to do it for `EF Core 5` depending on how the Filter already built-in on EF Core evolve.
