### ISSUE TITLE
Another way to initialize filters besides calling modelBuilder.Filter?

### ISSUE THREAD

**Issue by madatanic** [zzzprojects/EntityFramework.DynamicFilters#161]
Our code caches DbCompiledModel to improve EF startup performance which causes OnModelCreating not to be called on subsequent startups when there are no changes in the code first models. This results in modelBuilder.Filter not being executed as well. Is there an alternative way to initialize the dynamic filters besides within OnModelCreating?

**Comment by JonathanMagnan** [comment]
Hello @madatanic ,

Unfortunately no, we already tried in the past by using the `DbCompiledModel` but we didn't have found any solution yet ;(

This task is already in our wish-list, so we might eventually try again but at this moment, there is no know solution.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
