### ISSUE TITLE
Enum-of-byte is unnecessarily cast to int

### ISSUE THREAD

**Issue by TobiasMarklund** [zzzprojects/EntityFramework.DynamicFilters#162]
### Description
When adding a filter to a byte-backed enum field which is stored as a (in Sql Server) 'tinyint' column an unnecessary CAST ( x AS int ) is generated, causing unnecessary strain on the database. 

E.g. a field of the following type:
    public enum CustomerStatus : byte {
        Normal = 0,
        Inactive = 1,
        Deleted = 2
    }

With the following filter:
    modelBuilder.Filter("IsNotDeleted", (Customer d, CustomerStatus status) => d.Status != status, CustomerStatus.Deleted);

Will generate the following SQL:
SELECT 
    [Extent1].[CustomerID] AS [CustomerID], 
    [Extent1].[Name] AS [Name], 
    [Extent1].[Status] AS [Status]
    FROM [dbo].[Customers] AS [Extent1]
    WHERE ( CAST( [Extent1].[Status] AS int) <>  CAST( @DynamicFilterParam_000001 AS int)) 

The expected result should be:
SELECT 
    [Extent1].[CustomerID] AS [CustomerID], 
    [Extent1].[Name] AS [Name], 
    [Extent1].[Status] AS [Status]
    FROM [dbo].[Customers] AS [Extent1]
    WHERE ( [Extent1].[Status] <> @DynamicFilterParam_000001 ) 

### Fiddle or Project
https://dotnetfiddle.net/3iJBCx

### Further technical details
- EF version: 6.3
- EF DynamicFilters version: 3.1.0
- Database Provider: SqlServer

**Comment by JonathanMagnan** [comment]
Hello @TobiasMarklund ,

Thank you for reporting.

We tried the same Fiddle without our library and as expected, there is no CAST.

We will look at why this cast happen in the library

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @TobiasMarklund ,

We looked at it this weekend, however, we didn't succeed to find a solution.

We tried to move some code but unfortunately, the cast was always required at the end when comparing both `DbExpression`.

So unless you have found something on your side that might worth to investigate, I believe we will close this issue since we have not found an alternative way to make it works without the cast.

**Comment by TobiasMarklund** [comment]
Why did you close this?

**Comment by JonathanMagnan** [comment]
Oops! Sorry,

The issue was marked as to be "closed" but the status was not updated with your last answer. So we closed it by mistake ;(

Now opened ;)

**Comment by JonathanMagnan** [comment]
Hello @TobiasMarklund ,

Thank you for your contribution.

The v3.1.1 has been released. It includes your both pull requests.
