### ISSUE TITLE
IsFilterEnabled returns true for non-existent filter

### ISSUE THREAD

**Issue by jwcde** [zzzprojects/EntityFramework.DynamicFilters#165]
https://github.com/zzzprojects/EntityFramework.DynamicFilters/blob/99aafe5cb2690f6920cd7372976dc83c1f199395/src/EntityFramework.DynamicFilters.Shared/DynamicFilterExtensions.cs#L847-L848

Does this have to return true here? This returns true even if filter does not exist, which is misleading. It could throw an exception if the filter doesn't exist, or failing that, at least return false (which is less misleading)?

**Comment by JonathanMagnan** [comment]
Hello @jwcde ,

You might be right.

However, for backward compatibility, it's better to keep it like this.
