### ISSUE TITLE
Concurrency error when PreventDisabledFilterConditions is called

### ISSUE THREAD

**Issue by prvyk** [zzzprojects/EntityFramework.DynamicFilters#174]
> System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
>    at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
>    at 
> EntityFramework.DynamicFilters.DynamicFilterExtensions.PreventDisabledFilterConditions(DbModelBuilder modelBuilder, String filterName)

Affected software is a ASP.NET Core 3.1 web API using EFv6.44, a restart stopped the error from recurring. I've been using the package for several years (most of the time with .NET Framework) without this issue, this must be a very rare race condition.
I guess the fix is using ConcurrenctDictionary<> Instead of HashSet<>, like the other variables in DynamicFilterExtensions class.

**Comment by JonathanMagnan** [comment]
Hello @prvyk ,

The v3.2.2 has been released.

In this version, we changed the `HashSet` for a `ConcurrenctDictionary` like you proposed.

Let me know if that fix your issue or you still have it.

---

**Is this library useful to you?** Please help us by [becoming a sponsor](https://github.com/sponsors/zzzprojects) to keep it alive and supported.

**Comment by prvyk** [comment]
Thanks for working on this package!

The code works for me. I couldn't find a scenario which would replicate the previous error, so it's not a complete test. But I don't see a problem now, and the fix should handle this if it recurs.
